# Encoding Categorical Data

# 1. Label Encoding

Label Encoding assigns a unique number (integer) to each category. It is useful for ordinal data, where categories have an inherent order (e.g., "Low", "Medium", "High").

In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

data = {'Weather': ['Sunny', 'Cloudy', 'Rainy', 'Sunny', 'Rainy']}
df = pd.DataFrame(data)
df

C:\Users\polro\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

  Weather
0   Sunny
1  Cloudy
2   Rainy
3   Sunny
4   Rainy

In [5]:
le=LabelEncoder()
df['Wheather_Encoded']=le.fit_transform(df['Weather'])
df

  Weather  Wheather_Encoded
0   Sunny                 2
1  Cloudy                 0
2   Rainy                 1
3   Sunny                 2
4   Rainy                 1

# 2. One Hot Encoder

One-Hot Encoding creates a new binary column for each category. It is useful for nominal data (data without any specific order, like colors, countries, etc.).

method 1. using pd.get_dummies()

In [19]:
data = {'Color': ['Red', 'Blue', 'Green', 'Blue', 'Red']}
df = pd.DataFrame(data)
df[['Color_Red','Color_Blue','Color_Green']]=pd.get_dummies(df)
df.drop(columns='Color',inplace=True)
df

   Color_Red  Color_Blue  Color_Green
0          0           0            1
1          1           0            0
2          0           1            0
3          1           0            0
4          0           0            1

Method 2. Using OneHotEncoder from sklearn

In [38]:
from sklearn.preprocessing import OneHotEncoder
data = {'Color': ['Red', 'Blue', 'Green', 'Blue', 'Red']}
df = pd.DataFrame(data)
ohe=OneHotEncoder(sparse=False)
encoded_array=ohe.fit_transform(df[['Color']])
one_hot_encode=pd.DataFrame(encoded_array,columns=ohe.get_feature_names_out(['Color']))
one_hot_encode

   Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         1.0          0.0        0.0
4         0.0          0.0        1.0